[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli']

[variables]
DB_CONNECTION = 'mysql'

[phases.install]
cmds = [
    'mkdir -p bootstrap/cache storage/logs storage/framework/cache/data storage/framework/sessions storage/framework/testing storage/framework/views',
    'chmod -R 755 bootstrap/cache storage',
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'chmod -R 755 bootstrap/cache storage'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"